export const PROJECT_STATUSES = [
  'In Discussion',
  'Project Started',
  'Awaiting Documents',
  'All Documents Sent',
  'Document Correction / Update',
  'Project Filing In Progress',
  'Project Filing Done',
  'Project Approval Pending',
  'Project Modification Requested',
  'Project Approved',
  'Post Approval Formalities Pending',
  'Project Completed',
]

const BASE_DOCUMENTS = [
  {
    id: 'doc-project-report',
    fieldName: 'Project Report',
    file: {
      name: 'project_report.pdf',
      type: 'PDF',
      size: '1.4 MB',
      uploadedOn: '12 May 2024, 10:30 AM',
    },
  },
  {
    id: 'doc-dpr',
    fieldName: 'DPR / Feasibility Report',
    file: {
      name: 'dpr_report.pdf',
      type: 'PDF',
      size: '2.1 MB',
      uploadedOn: '11 May 2024, 04:15 PM',
    },
  },
  {
    id: 'doc-land',
    fieldName: 'Land Ownership Proof',
    file: null,
  },
  {
    id: 'doc-financial',
    fieldName: 'Financial Projection',
    file: {
      name: 'financials.xlsx',
      type: 'Excel',
      size: '842 KB',
      uploadedOn: '09 May 2024, 09:45 AM',
    },
  },
]

const INITIAL_PROJECTS = [
  {
    id: 'project-solar-panel',
    projectTitle: 'Solar Panel Manufacturing',
    projectDescription: 'Production unit for solar panels with manufacturing capacity of 100 MW per annum.',
    status: 'In Discussion',
    lastUpdated: '12 May 2024, 10:30 AM',
    submittedByType: 'Business Associate',
    associateName: 'Vikram Kumar',
    associateEmail: 'vikram.kumar@example.com',
    clientName: 'Priya Nair',
    clientEmail: 'priya.nair@example.com',
    clientPhone: '+91 98765 43210',
    sectionCode: 'C',
    sectionName: 'Manufacturing',
    divisionCode: '27',
    divisionName: 'Manufacture of electrical equipment',
    groupCode: '271',
    groupName: 'Manufacture of electric motors, generators and transformers',
    classCode: '2710',
    className: 'Manufacture of electric motors, generators and transformers',
    nicCode: '29309',
    nicName: 'Manufacture of electrical equipment',
    documents: BASE_DOCUMENTS,
    notes: 'Client is evaluating machinery quotations and subsidy eligibility.',
  },
  {
    id: 'project-it-services',
    projectTitle: 'IT Solutions and Services',
    projectDescription: 'Software development and IT consulting services for domestic SME clients.',
    status: 'Project Filing In Progress',
    lastUpdated: '17 October 2024, 09:45 AM',
    submittedByType: 'Business Associate',
    associateName: 'Pooja Shah',
    associateEmail: 'pooja.shah@example.com',
    clientName: 'Ananya Iyer',
    clientEmail: 'ananya.iyer@example.com',
    clientPhone: '+91 99887 77665',
    sectionCode: 'J',
    sectionName: 'Information and Communication',
    divisionCode: '62',
    divisionName: 'Computer programming, consultancy and related activities',
    groupCode: '620',
    groupName: 'Computer programming, consultancy and related activities',
    classCode: '6202',
    className: 'Computer consultancy and computer facilities management',
    nicCode: '62020',
    nicName: 'Computer programming, consultancy and related activities',
    documents: [
      ...BASE_DOCUMENTS.slice(0, 2),
      { id: 'doc-udyam', fieldName: 'Udyam Registration', file: null },
    ],
    notes: '',
  },
  {
    id: 'project-organic-fertilizer',
    projectTitle: 'Organic Fertilizer Unit',
    projectDescription: 'Manufacturing unit for organic fertilizers and soil enrichment products.',
    status: 'Awaiting Documents',
    lastUpdated: '10 September 2024, 02:20 PM',
    submittedByType: 'Self',
    clientName: 'Rohan Mehta',
    clientEmail: 'rohan.mehta@example.com',
    clientPhone: '+91 91234 56780',
    sectionCode: 'C',
    sectionName: 'Manufacturing',
    divisionCode: '20',
    divisionName: 'Manufacture of chemicals and chemical products',
    groupCode: '202',
    groupName: 'Manufacture of other chemical products',
    classCode: '2021',
    className: 'Manufacture of pesticides and other agrochemical products',
    nicCode: '23999',
    nicName: 'Manufacture of other non-metallic mineral products',
    documents: BASE_DOCUMENTS.map((document) => ({ ...document, file: null })),
    notes: 'Awaiting land documents and provisional financials.',
  },
  {
    id: 'ba-project-cold-storage',
    projectTitle: 'Cold Storage Facility',
    projectDescription: 'Cold storage facility for FreshMart Retail Pvt. Ltd.',
    status: 'Project Approved',
    lastUpdated: '06 May 2024',
    submittedByType: 'Business Associate',
    associateName: 'Vikram Kumar',
    associateEmail: 'vikram.kumar@example.com',
    clientName: 'FreshMart Retail Pvt. Ltd.',
    clientEmail: 'freshmart@example.com',
    clientPhone: '+91 90000 00001',
    sectionCode: 'H',
    sectionName: 'Transportation and Storage',
    divisionCode: '52',
    divisionName: 'Warehousing and support activities for transportation',
    groupCode: '521',
    groupName: 'Warehousing and storage',
    classCode: '5210',
    className: 'Warehousing and storage',
    nicCode: '52102',
    nicName: 'Storage and warehousing',
    documents: BASE_DOCUMENTS.map((document) => ({ ...document, file: document.file ? { ...document.file } : null })),
    notes: 'Filed by business associate Vikram Kumar.',
  },
  {
    id: 'ba-project-organic-fertilizer',
    projectTitle: 'Organic Fertilizer Unit',
    projectDescription: 'Organic fertilizer unit for GreenEarth Organics.',
    status: 'Awaiting Documents',
    lastUpdated: '11 May 2024',
    submittedByType: 'Business Associate',
    associateName: 'Vikram Kumar',
    associateEmail: 'vikram.kumar@example.com',
    clientName: 'GreenEarth Organics',
    clientEmail: 'greenearth@example.com',
    clientPhone: '+91 90000 00007',
    sectionCode: 'C',
    sectionName: 'Manufacturing',
    divisionCode: '20',
    divisionName: 'Manufacture of chemicals and chemical products',
    groupCode: '202',
    groupName: 'Manufacture of other chemical products',
    classCode: '2021',
    className: 'Manufacture of pesticides and other agrochemical products',
    nicCode: '23999',
    nicName: 'Manufacture of other non-metallic mineral products',
    documents: BASE_DOCUMENTS.map((document) => ({ ...document, file: document.file ? { ...document.file } : null })),
    notes: 'Filed by business associate Vikram Kumar.',
  },
  {
    id: 'ba-project-charging',
    projectTitle: 'EV Charging Station Network',
    projectDescription: 'EV charging station network for ChargeUp Mobility Pvt. Ltd.',
    status: 'Project Filing Done',
    lastUpdated: '05 May 2024',
    submittedByType: 'Business Associate',
    associateName: 'Vikram Kumar',
    associateEmail: 'vikram.kumar@example.com',
    clientName: 'ChargeUp Mobility Pvt. Ltd.',
    clientEmail: 'chargeup@example.com',
    clientPhone: '+91 90000 00002',
    sectionCode: 'D',
    sectionName: 'Electricity, gas, steam and air conditioning supply',
    divisionCode: '35',
    divisionName: 'Electricity, gas, steam and air conditioning supply',
    groupCode: '351',
    groupName: 'Electric power generation, transmission and distribution',
    classCode: '3510',
    className: 'Electric power generation, transmission and distribution',
    nicCode: '35105',
    nicName: 'Electric power generation',
    documents: BASE_DOCUMENTS.map((document) => ({ ...document, file: document.file ? { ...document.file } : null })),
    notes: 'Filed by business associate Vikram Kumar.',
  },
  {
    id: 'ba-project-agri-export',
    projectTitle: 'Agri Produce Export Unit',
    projectDescription: 'Agri produce export unit for Global Agri Exports.',
    status: 'In Discussion',
    lastUpdated: '04 May 2024',
    submittedByType: 'Business Associate',
    associateName: 'Vikram Kumar',
    associateEmail: 'vikram.kumar@example.com',
    clientName: 'Global Agri Exports',
    clientEmail: 'exports@example.com',
    clientPhone: '+91 90000 00003',
    sectionCode: 'G',
    sectionName: 'Wholesale and retail trade',
    divisionCode: '46',
    divisionName: 'Wholesale trade, except of motor vehicles and motorcycles',
    groupCode: '463',
    groupName: 'Wholesale of food, beverages and tobacco',
    classCode: '4630',
    className: 'Wholesale of food, beverages and tobacco',
    nicCode: '46309',
    nicName: 'Wholesale of other food products',
    documents: BASE_DOCUMENTS.map((document) => ({ ...document, file: document.file ? { ...document.file } : null })),
    notes: 'Filed by business associate Vikram Kumar.',
  },
  {
    id: 'ba-project-textile',
    projectTitle: 'Textile Processing Unit',
    projectDescription: 'Textile processing unit for Shah Textiles LLP.',
    status: 'Project Started',
    lastUpdated: '08 May 2024',
    submittedByType: 'Business Associate',
    associateName: 'Pooja Shah',
    associateEmail: 'pooja.shah@example.com',
    clientName: 'Shah Textiles LLP',
    clientEmail: 'shahtextiles@example.com',
    clientPhone: '+91 90000 00004',
    sectionCode: 'C',
    sectionName: 'Manufacturing',
    divisionCode: '13',
    divisionName: 'Manufacture of textiles',
    groupCode: '131',
    groupName: 'Spinning, weaving and finishing of textiles',
    classCode: '1312',
    className: 'Weaving of textiles',
    nicCode: '13129',
    nicName: 'Other weaving of textiles',
    documents: BASE_DOCUMENTS.map((document) => ({ ...document, file: document.file ? { ...document.file } : null })),
    notes: 'Filed by business associate Pooja Shah.',
  },
  {
    id: 'ba-project-packaging',
    projectTitle: 'Eco Packaging Plant',
    projectDescription: 'Eco packaging plant for GreenPack Industries.',
    status: 'Project Completed',
    lastUpdated: '02 May 2024',
    submittedByType: 'Business Associate',
    associateName: 'Pooja Shah',
    associateEmail: 'pooja.shah@example.com',
    clientName: 'GreenPack Industries',
    clientEmail: 'greenpack@example.com',
    clientPhone: '+91 90000 00005',
    sectionCode: 'C',
    sectionName: 'Manufacturing',
    divisionCode: '17',
    divisionName: 'Manufacture of paper and paper products',
    groupCode: '170',
    groupName: 'Manufacture of paper and paper products',
    classCode: '1702',
    className: 'Manufacture of corrugated paper and paperboard',
    nicCode: '17021',
    nicName: 'Manufacture of corrugated paper and paperboard',
    documents: BASE_DOCUMENTS.map((document) => ({ ...document, file: document.file ? { ...document.file } : null })),
    notes: 'Completed project. Details are locked from further editing.',
  },
  {
    id: 'ba-project-food',
    projectTitle: 'Food Processing Expansion',
    projectDescription: 'Food processing expansion for PureFoods India.',
    status: 'All Documents Sent',
    lastUpdated: '30 April 2024',
    submittedByType: 'Business Associate',
    associateName: 'Pooja Shah',
    associateEmail: 'pooja.shah@example.com',
    clientName: 'PureFoods India',
    clientEmail: 'purefoods@example.com',
    clientPhone: '+91 90000 00006',
    sectionCode: 'C',
    sectionName: 'Manufacturing',
    divisionCode: '10',
    divisionName: 'Manufacture of food products',
    groupCode: '103',
    groupName: 'Processing and preserving of fruit and vegetables',
    classCode: '1030',
    className: 'Processing and preserving of fruit and vegetables',
    nicCode: '10309',
    nicName: 'Processing and preserving of fruits and vegetables',
    documents: BASE_DOCUMENTS.map((document) => ({ ...document, file: document.file ? { ...document.file } : null })),
    notes: 'Filed by business associate Pooja Shah.',
  },
]

let projectStore = INITIAL_PROJECTS.map((project) => ({
  ...project,
  documents: project.documents.map((document) => ({
    ...document,
    file: document.file ? { ...document.file } : null,
  })),
}))

export function getProjects() {
  return projectStore.map((project) => ({
    ...project,
    documents: project.documents.map((document) => ({
      ...document,
      file: document.file ? { ...document.file } : null,
    })),
  }))
}

export function getProjectById(projectId) {
  return getProjects().find((project) => project.id === projectId)
}

export function updateProject(projectId, updater) {
  projectStore = projectStore.map((project) =>
    project.id === projectId ? updater(project) : project,
  )
  return getProjectById(projectId)
}
