export const SERVICE_CATEGORIES = [
  'Government Funding',
  'Startup Funding',
  'Financing Options',
  'Special Categories',
]

export const mockServices = [
  {
    id: 'startup-india',
    name: 'Startup India Registration',
    slug: 'startup-india-registration',
    category: 'Government Funding',
    status: 'Published',
    order: 1,
    lastUpdated: '12 May 2024, 10:30 AM',
    image: '/assets/img/service/service-img-1.png',
    highlights: [
      'Tax exemptions for 3 years',
      'Easy winding up of company',
      'Self-certification under labor laws',
      'Access to Government funds',
    ],
    shortDescription: 'Get your startup recognized by DPIIT and unlock numerous benefits.',
    content: '<h2>Introduction</h2><p>Startup India is a flagship initiative of the Government of India...</p>',
  },
  {
    id: 'msme-registration',
    name: 'MSME / Udyam Registration',
    slug: 'msme-registration',
    category: 'Government Funding',
    status: 'Published',
    order: 2,
    lastUpdated: '11 May 2024, 04:15 PM',
    image: '/assets/img/service/service-img-2.png',
    highlights: [
      'Collateral free loans',
      'Subsidy on patent registration',
      'Exemption on overdraft interest rate',
      'Protection against delayed payments',
    ],
    shortDescription: 'Register your business under MSME and avail various government schemes.',
  },
  {
    id: 'angel-investment',
    name: 'Angel Investment Connect',
    slug: 'angel-investment-connect',
    category: 'Startup Funding',
    status: 'Published',
    order: 3,
    lastUpdated: '10 May 2024, 11:20 AM',
    image: '/assets/img/service/service-img-3.png',
    highlights: [
      'Network of 500+ Angel Investors',
      'Pitch deck assistance',
      'Valuation support',
      'Term sheet negotiation',
    ],
    shortDescription: 'We connect early-stage startups with active angel investors.',
  },
  {
    id: 'project-finance',
    name: 'Project Finance',
    slug: 'project-finance',
    category: 'Financing Options',
    status: 'Draft',
    order: 4,
    lastUpdated: '09 May 2024, 09:45 AM',
    image: '/assets/img/service/service-img-4.png',
    highlights: [
      'Debt financing for large projects',
      'Flexible repayment schedules',
      'Competitive interest rates',
      'End-to-end documentation support',
    ],
    shortDescription: 'Customized financial solutions for infrastructure and industrial projects.',
  },
]
