export const GOVT_SCHEME_CATEGORIES = [
  'Employment Generation',
  'Financial Support',
  'MSME Support',
  'Startup Support',
  'Tax Benefits',
  'Capital Subsidy',
  'Credit Guarantee',
  'Interest Subsidy',
  'Export Incentives',
  'Exemption & Waves',
  'Non-Monetary Support',
  'Reimbursement',
]

export const MINISTRIES = [
  'Ministry of MSME',
  'Ministry of Finance',
  'Ministry of Agriculture & Farmers Welfare',
  'Ministry of Commerce & Industry',
  'Ministry of Electronics & IT',
  'Ministry of Food Processing Industries',
  'Ministry of Textiles',
  'Ministry of Health & Family Welfare',
  'Ministry of New & Renewable Energy',
  'Department of Financial Services',
  'Department for Promotion of Industry and Internal Trade (DPIIT)',
]

export const mockGovernmentSchemes = [
  {
    id: 'pmegp-scheme',
    name: 'PMEGP Scheme',
    fullTitle: "Prime Minister's Employment Generation Programme",
    slug: 'pmegp-scheme',
    ministry: 'Ministry of MSME',
    categories: ['Employment Generation', 'Financial Support', 'MSME Support'],
    status: 'Published',
    order: 1,
    lastUpdated: '12 May 2024, 10:30 AM',
    shortDescription: 'Credit-linked subsidy scheme for setting up new micro enterprises and generating employment opportunities.',
    highlights: [
      'Subsidy up to 35% of project cost',
      'Collateral-free loans',
      'Promotes self-employment',
      'Supports rural and urban enterprises',
    ],
    tags: ['Subsidy', 'Loan Support', 'Self Employment', 'Business Setup'],
    sections: [
      { title: 'Objective', content: 'To generate employment opportunities in rural as well as urban areas of the country through setting up of new self-employment projects/projects/micro enterprises.' },
      { title: 'Beneficiary', content: 'Any individual, above 18 years of age. At least VIII standard pass for projects costing above Rs.10 lakh in the manufacturing sector and above Rs. 5 lakh in the business /service sector.' },
      { title: 'Benefits', content: 'The maximum cost of the project/unit admissible in manufacturing sector is Rs. 50 lakhs and in the business/service sector is Rs. 20 lakhs.' },
      { title: 'Eligibility', content: 'Self Help Groups, Institutions registered under Societies Registration Act, 1860, Production Co-operative Societies, and Charitable Trusts.' },
    ],
    documents: [
      'Aadhar Card',
      'PAN Card',
      'Project Report',
      'Caste Certificate (if applicable)',
      'Educational Qualification Certificate',
    ],
    eligibilityCriteria: 'Individuals above 18 years, SHGs, Societies, Trusts.',
  },
  {
    id: 'stand-up-india',
    name: 'Stand Up India Scheme',
    fullTitle: 'Stand Up India Scheme',
    slug: 'stand-up-india',
    ministry: 'Department of Financial Services',
    categories: ['Entrepreneurship', 'Financial Support'],
    status: 'Published',
    order: 2,
    lastUpdated: '11 May 2024, 04:15 PM',
    shortDescription: 'Facilitates bank loans between 10 lakh and 1 Crore to at least one SC/ST and one woman borrower per bank branch.',
    highlights: [
      'Loan up to 1 Crore',
      'Focus on SC/ST and Women',
      'Greenfield enterprises',
      'Handholding support',
    ],
    tags: ['Women Empowerment', 'SC/ST Support', 'Business Loan'],
    sections: [
      { title: 'Objective', content: 'To facilitate bank loans between Rs. 10 lakh and Rs. 1 Crore to at least one Scheduled Caste (SC) or Scheduled Tribe (ST) borrower and at least one woman borrower per bank branch for setting up a greenfield enterprise.' },
    ],
  },
  {
    id: 'startup-india-initiative',
    name: 'Startup India Initiative',
    fullTitle: 'Startup India Initiative',
    slug: 'startup-india-initiative',
    ministry: 'Department for Promotion of Industry and Internal Trade (DPIIT)',
    categories: ['Startup Support', 'Tax Benefits'],
    status: 'Published',
    order: 3,
    lastUpdated: '10 May 2024, 11:20 AM',
    shortDescription: 'Flagship initiative intended to build a strong ecosystem for nurturing innovation and Startups in the country.',
  },
  {
    id: 'mudra-loan',
    name: 'Mudra Loan Scheme',
    fullTitle: 'Pradhan Mantri Mudra Yojana',
    slug: 'mudra-loan',
    ministry: 'Ministry of Finance',
    categories: ['Financial Support'],
    status: 'Published',
    order: 4,
    lastUpdated: '09 May 2024, 09:45 AM',
    shortDescription: 'Provides loans up to 10 lakh to the non-corporate, non-farm small/micro enterprises.',
  },
]
